test/force-app/main/default/objects/Account/fields/Compte_Facturation__c.field-meta.xml
<CustomField>
    <fullName>Compte_Facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Account/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <label>Identification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/Projet__c.object-meta.xml
<CustomObject>
    <label>Projet</label>
    <nameField>
        <label>Nom projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Projet__c/fields/A_facturer__c.field-meta.xml
<CustomField>
    <fullName>A_facturer__c</fullName>
    <label>A facturer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Adresse_de_Livraison_2__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_Livraison_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact de livraison</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Adresse de Livraison 2)</relationshipLabel>
    <relationshipName>Projets1</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Adresse_de_Livraison__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_Livraison__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse de Livraison</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Adresse de Livraison)</relationshipLabel>
    <relationshipName>Projets5</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Architecte__c.field-meta.xml
<CustomField>
    <fullName>Architecte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Architecte /EG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Architecte)</relationshipLabel>
    <relationshipName>Projets2</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Architecte_EG_Contact__c.field-meta.xml
<CustomField>
    <fullName>Architecte_EG_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact (Architecte/EG)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Architecte / EG - Contact)</relationshipLabel>
    <relationshipName>Projets9</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Avance_client__c.field-meta.xml
<CustomField>
    <fullName>Avance_client__c</fullName>
    <label>Avance client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Calculation_net_avec_provision__c.field-meta.xml
<CustomField>
    <fullName>Calculation_net_avec_provision__c</fullName>
    <label>Calculation PR (avec provisions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Calculation_net_sans_provision__c.field-meta.xml
<CustomField>
    <fullName>Calculation_net_sans_provision__c</fullName>
    <label>Calculation PR (sans provisions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Compte_Facturation__c.field-meta.xml
<CustomField>
    <fullName>Compte_Facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Compte Facturation)</relationshipLabel>
    <relationshipName>Projets3</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Confirme__c.field-meta.xml
<CustomField>
    <fullName>Confirme__c</fullName>
    <label>Confirmé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Correction_confirm__c.field-meta.xml
<CustomField>
    <fullName>Correction_confirm__c</fullName>
    <label>Correction confirmé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Date_de_fermeture__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fermeture__c</fullName>
    <label>Date d&apos;adjudication</label>
    <type>Date</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Etape__c.field-meta.xml
<CustomField>
    <fullName>Etape__c</fullName>
    <label>Étape</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunité</fullName>
                <default>true</default>
                <label>Opportunité</label>
            </value>
            <value>
                <fullName>Attribution</fullName>
            </value>
            <value>
                <fullName>Ouvert</fullName>
            </value>
            <value>
                <fullName>Ouvert (Offre envoyée)</fullName>
                <label>Offre envoyée</label>
            </value>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Confirmé</fullName>
            </value>
            <value>
                <fullName>Exécuté</fullName>
            </value>
            <value>
                <fullName>Facturé</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Pas exécuté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Facturation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facturation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact facturation</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Autre contact)</relationshipLabel>
    <relationshipName>Projets3</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <label>Facturé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Famille_commerciale__c.field-meta.xml
<CustomField>
    <fullName>Famille_commerciale__c</fullName>
    <label>Famille commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Secteur_d_activite__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>fc.00.54 Boutique</fullName>
                <label>Boutique</label>
            </value>
            <value>
                <fullName>fc.00.55 Corner</fullName>
                <label>Corner</label>
            </value>
            <value>
                <fullName>fc.00.56 Shop in shop</fullName>
                <label>Shop in shop</label>
            </value>
            <value>
                <fullName>fc.00.57 Pop-up</fullName>
                <label>Pop-up</label>
            </value>
            <value>
                <fullName>fc.00.58 Mobilier de série</fullName>
                <label>Mobilier de série</label>
            </value>
            <value>
                <fullName>fc.00.59 Stands d&apos;exposition</fullName>
                <label>Stands d&apos;exposition</label>
            </value>
            <value>
                <fullName>fc.01.04 Hôtellerie</fullName>
                <label>Hôtellerie</label>
            </value>
            <value>
                <fullName>fc.01.06 Santé</fullName>
                <label>Santé</label>
            </value>
            <value>
                <fullName>fc.01.07 Musées</fullName>
                <label>Musées</label>
            </value>
            <value>
                <fullName>fc.01.08 Commercial</fullName>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>fc.01.09 Immeuble</fullName>
                <label>Immeuble</label>
            </value>
            <value>
                <fullName>fc.01.10 Privé</fullName>
                <label>Privé</label>
            </value>
            <value>
                <fullName>fc.01.14 Administratif</fullName>
                <label>Administratif</label>
            </value>
            <value>
                <fullName>fc.01.16 Scolaire</fullName>
                <label>Scolaire</label>
            </value>
            <value>
                <fullName>fc.01.17 Airkel</fullName>
                <label>Airkel</label>
            </value>
            <value>
                <fullName>fc.01.18 Écrin/PLV</fullName>
                <label>Écrin/PLV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Genre_Projet_SF__c.field-meta.xml
<CustomField>
    <fullName>Genre_Projet_SF__c</fullName>
    <label>Typologie projet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Projet classique</fullName>
            </value>
            <value>
                <fullName>Projet multiple</fullName>
            </value>
            <value>
                <fullName>Projet PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Maitre_d_ouvrage__c.field-meta.xml
<CustomField>
    <fullName>Maitre_d_ouvrage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client/MO</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Maitre d’ouvrage)</relationshipLabel>
    <relationshipName>Projets1</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Maitre_d_ouvrage_Contact__c.field-meta.xml
<CustomField>
    <fullName>Maitre_d_ouvrage_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact (Client/MO)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Maitre d’ouvrage - Contact)</relationshipLabel>
    <relationshipName>Projets8</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Mandant__c.field-meta.xml
<CustomField>
    <fullName>Mandant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mandant</label>
    <referenceTo>Soci_t_du_groupe__c</referenceTo>
    <relationshipLabel>Projets</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant estimatif</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Numero_projet__c.field-meta.xml
<CustomField>
    <fullName>Numero_projet__c</fullName>
    <label>Numéro projet</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Offert__c.field-meta.xml
<CustomField>
    <fullName>Offert__c</fullName>
    <label>Offert</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Paiement_client_recevoir__c.field-meta.xml
<CustomField>
    <fullName>Paiement_client_recevoir__c</fullName>
    <label>À recevoir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Paye__c.field-meta.xml
<CustomField>
    <fullName>Paye__c</fullName>
    <label>Payé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Reference_client__c.field-meta.xml
<CustomField>
    <fullName>Reference_client__c</fullName>
    <label>Référence client</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Responsable_commercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable commercial</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Responsable commercial)</relationshipLabel>
    <relationshipName>ProjetsTiDy</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Responsable_Projet_Contact__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Projet_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sous-traitant 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/SAIS_com_ID__c.field-meta.xml
<CustomField>
    <fullName>SAIS_com_ID__c</fullName>
    <label>SAIS _com ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Type_projet__c.field-meta.xml
<CustomField>
    <fullName>Type_projet__c</fullName>
    <label>Genre projet</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Soci_t_du_groupe__c/Soci_t_du_groupe__c.object-meta.xml
<CustomObject>
    <label>Société du groupe</label>
    <nameField>
        <label>Nom de Société du groupe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sociétés du groupe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Soci_t_du_groupe__c/fields/IdentifiantSoci_t_grpupe__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantSoci_t_grpupe__c</fullName>
    <label>IdentifiantSociétégrpupe</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/classes/TrivisoProjetMapper_TEST.cls
@isTest
private class TrivisoProjetMapper_TEST {

    @testSetup
    static void setUpTestData() {
        TriggerHandler.bypassProjetTrigger = true;
        TrivisoDataFactory.createProjetForTrivisoMapper(true);
    }

    @isTest
    static void testMapFromProjet_AllFields() {
        Projet__c queriedProjet = [
            SELECT Id, Name, SAIS_com_ID__c, Numero_projet__c, Reference_client__c, Etape__c, Type_projet__c,
                   Famille_commerciale__c, Date_de_fermeture__c,
                   Calculation_net_sans_provision__c, Calculation_net_avec_provision__c,
                   Offert__c, Confirme__c, Correction_confirm__c, Facture__c, Paye__c,
                   Montant__c, A_facturer__c, Avance_client__c, Paiement_client_recevoir__c,
                   Compte_Facturation__c, Compte_Facturation__r.Identification__c,
                   Adresse_de_Livraison__r.Identification__c,
                   Maitre_d_ouvrage__r.Identification__c,
                   Architecte__r.Identification__c,
                   Mandant__r.IdentifiantSoci_t_grpupe__c,
                   Responsable_commercial__r.Identification__c,
                   Responsable_Projet_Contact__c, Responsable_Projet_Contact__r.Identification__c,
                   Facturation_Contact__r.Identification__c,
                   Adresse_de_Livraison_2__r.Identification__c,
                   Maitre_d_ouvrage_Contact__r.Identification__c,
                   Architecte_EG_Contact__r.Identification__c,
                   Genre_Projet_SF__c,
                   LastModifiedDate
            FROM Projet__c
            WHERE Name LIKE 'TRIVISO_PROJET_MAPPER_%'
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        Test.startTest();
        TrivisoProjetRecord record = TrivisoProjetMapper.mapFromProjet(queriedProjet);
        Test.stopTest();
        System.assertEquals(queriedProjet.Id, record.saisComSalesforceId, 'saisComSalesforceId');
        System.assertEquals('', record.saisComId, 'saisComId');
        System.assertEquals(queriedProjet.Numero_projet__c != null ? queriedProjet.Numero_projet__c : '', record.saisComIdentification, 'saisComIdentification');
        System.assertEquals(queriedProjet.Name, record.saisComDescription, 'saisComDescription');
        System.assertEquals(queriedProjet.Reference_client__c != null ? queriedProjet.Reference_client__c : '', record.saisComNoCommClient, 'saisComNoCommClient');
        System.assertEquals(queriedProjet.Etape__c != null ? String.valueOf(queriedProjet.Etape__c) : '', record.saisComEtatId, 'saisComEtatId');
        System.assertEquals(queriedProjet.Type_projet__c != null ? queriedProjet.Type_projet__c : '', record.saisComGenreProjet, 'saisComGenreProjet');
        System.assertEquals(queriedProjet.Famille_commerciale__c != null ? queriedProjet.Famille_commerciale__c : '', record.saisComFamDesignation, 'saisComFamDesignation');
        System.assert(record.saisComDateOuvert.contains('15.03.2024'), 'saisComDateOuvert');
        String factId = queriedProjet.Compte_Facturation__r != null && String.isNotBlank(queriedProjet.Compte_Facturation__r.Identification__c)
            ? queriedProjet.Compte_Facturation__r.Identification__c
            : '';
        String livrId = queriedProjet.Adresse_de_Livraison__r != null && String.isNotBlank(queriedProjet.Adresse_de_Livraison__r.Identification__c)
            ? queriedProjet.Adresse_de_Livraison__r.Identification__c
            : '';
        String moId = queriedProjet.Maitre_d_ouvrage__r != null && String.isNotBlank(queriedProjet.Maitre_d_ouvrage__r.Identification__c)
            ? queriedProjet.Maitre_d_ouvrage__r.Identification__c
            : '';
        String archId = queriedProjet.Architecte__r != null && String.isNotBlank(queriedProjet.Architecte__r.Identification__c)
            ? queriedProjet.Architecte__r.Identification__c
            : '';
        String mandId = queriedProjet.Mandant__r != null && String.isNotBlank(queriedProjet.Mandant__r.IdentifiantSoci_t_grpupe__c)
            ? queriedProjet.Mandant__r.IdentifiantSoci_t_grpupe__c
            : '';
        String respCommId = queriedProjet.Responsable_commercial__r != null && String.isNotBlank(queriedProjet.Responsable_commercial__r.Identification__c)
            ? queriedProjet.Responsable_commercial__r.Identification__c
            : '';
        String respProjId = queriedProjet.Responsable_Projet_Contact__r != null && String.isNotBlank(queriedProjet.Responsable_Projet_Contact__r.Identification__c)
            ? queriedProjet.Responsable_Projet_Contact__r.Identification__c
            : '';
        System.assertEquals(factId, record.saisComAdrFactId, 'saisComAdrFactId');
        System.assertEquals(queriedProjet.Compte_Facturation__c != null ? String.valueOf(queriedProjet.Compte_Facturation__c) : '', record.saisComAdrFactSalesforceId, 'saisComAdrFactSalesforceId');
        System.assertEquals(livrId, record.saisComAdrLivrId, 'saisComAdrLivrId');
        System.assertEquals(queriedProjet.Adresse_de_Livraison__c != null ? String.valueOf(queriedProjet.Adresse_de_Livraison__c) : '', record.saisComAdrLivrSalesforceId, 'saisComAdrLivrSalesforceId');
        System.assertEquals(moId, record.saisComAdrMoId, 'saisComAdrMoId');
        System.assertEquals(queriedProjet.Maitre_d_ouvrage__c != null ? String.valueOf(queriedProjet.Maitre_d_ouvrage__c) : '', record.saisComAdrMoSalesforceId, 'saisComAdrMoSalesforceId');
        System.assertEquals(archId, record.saisComAdrArchId, 'saisComAdrArchId');
        System.assertEquals(queriedProjet.Architecte__c != null ? String.valueOf(queriedProjet.Architecte__c) : '', record.saisComAdrArchSalesforceId, 'saisComAdrArchSalesforceId');
        System.assertEquals(respCommId, record.saisComAdrRespId, 'saisComAdrRespId');
        System.assertEquals(queriedProjet.Responsable_commercial__c != null ? String.valueOf(queriedProjet.Responsable_commercial__c) : '', record.saisComAdrRespSalesforceId, 'saisComAdrRespSalesforceId');
        System.assertEquals(mandId, record.saisComAdrMandId, 'saisComAdrMandId');
        System.assertEquals(queriedProjet.Mandant__c != null ? String.valueOf(queriedProjet.Mandant__c) : '', record.saisComAdrMandSalesforceId, 'saisComAdrMandSalesforceId');
        System.assertEquals(respProjId, record.saisComAdrRespProjId, 'saisComAdrRespProjId');
        System.assertEquals(queriedProjet.Responsable_Projet_Contact__c != null ? String.valueOf(queriedProjet.Responsable_Projet_Contact__c) : '', record.saisComAdrRespProjSalesforceId, 'saisComAdrRespProjSalesforceId');
        String factContId = queriedProjet.Facturation_Contact__r != null && String.isNotBlank(queriedProjet.Facturation_Contact__r.Identification__c)
            ? queriedProjet.Facturation_Contact__r.Identification__c : '';
        String livrContId = queriedProjet.Adresse_de_Livraison_2__r != null && String.isNotBlank(queriedProjet.Adresse_de_Livraison_2__r.Identification__c)
            ? queriedProjet.Adresse_de_Livraison_2__r.Identification__c : '';
        String moContId = queriedProjet.Maitre_d_ouvrage_Contact__r != null && String.isNotBlank(queriedProjet.Maitre_d_ouvrage_Contact__r.Identification__c)
            ? queriedProjet.Maitre_d_ouvrage_Contact__r.Identification__c : '';
        String archContId = queriedProjet.Architecte_EG_Contact__r != null && String.isNotBlank(queriedProjet.Architecte_EG_Contact__r.Identification__c)
            ? queriedProjet.Architecte_EG_Contact__r.Identification__c : '';
        System.assertEquals(factContId, record.saisComAdrFactContactId, 'saisComAdrFactContactId');
        System.assertEquals(null, record.saisComAdrFactContactSalesforceId, 'saisComAdrFactContactSalesforceId (non implemente dans le mapper)');
        System.assertEquals(livrContId, record.saisComAdrLivrContactId, 'saisComAdrLivrContactId');
        System.assertEquals(null, record.saisComAdrLivrContactSalesforceId, 'saisComAdrLivrContactSalesforceId (non implemente dans le mapper)');
        System.assertEquals(moContId, record.saisComAdrMoContactId, 'saisComAdrMoContactId');
        System.assertEquals(null, record.saisComAdrMoContactSalesforceId, 'saisComAdrMoContactSalesforceId (non implemente dans le mapper)');
        System.assertEquals(archContId, record.saisComAdrArchContactId, 'saisComAdrArchContactId');
        System.assertEquals(null, record.saisComAdrArchContactSalesforceId, 'saisComAdrArchContactSalesforceId (non implemente dans le mapper)');
        System.assertEquals(queriedProjet.Calculation_net_sans_provision__c != null ? String.valueOf(queriedProjet.Calculation_net_sans_provision__c) : '', record.saisComSomPrixRevientSansProvision, 'saisComSomPrixRevientSansProvision');
        System.assertEquals(queriedProjet.Calculation_net_avec_provision__c != null ? String.valueOf(queriedProjet.Calculation_net_avec_provision__c) : '', record.saisComSomPrixRevient, 'saisComSomPrixRevient');
        System.assertEquals(queriedProjet.Offert__c != null ? String.valueOf(queriedProjet.Offert__c) : '', record.saisComSomOffert, 'saisComSomOffert');
        System.assertEquals(queriedProjet.Confirme__c != null ? String.valueOf(queriedProjet.Confirme__c) : '', record.saisComSomConfirme, 'saisComSomConfirme');
        System.assertEquals(queriedProjet.Correction_confirm__c != null ? String.valueOf(queriedProjet.Correction_confirm__c) : '', record.saisComSomCorrectionConfirme, 'saisComSomCorrectionConfirme');
        System.assertEquals(queriedProjet.Facture__c != null ? String.valueOf(queriedProjet.Facture__c) : '', record.saisComSomFacture, 'saisComSomFacture');
        System.assertEquals(queriedProjet.Paye__c != null ? String.valueOf(queriedProjet.Paye__c) : '', record.saisComSomPaye, 'saisComSomPaye');
        System.assertEquals(queriedProjet.Montant__c != null ? String.valueOf(queriedProjet.Montant__c) : '', record.saisComSomDac, 'saisComSomDac');
        System.assertEquals(queriedProjet.A_facturer__c != null ? String.valueOf(queriedProjet.A_facturer__c) : '', record.saisComSomPotentielFacturation, 'saisComSomPotentielFacturation');
        System.assertEquals(queriedProjet.Avance_client__c != null ? String.valueOf(queriedProjet.Avance_client__c) : '', record.saisComSomAvanceClient, 'saisComSomAvanceClient');
        System.assertEquals(queriedProjet.Paiement_client_recevoir__c != null ? String.valueOf(queriedProjet.Paiement_client_recevoir__c) : '', record.saisComSomSoldeAPayeCHF, 'saisComSomSoldeAPayeCHF');
    }

    @isTest
    static void testMapProjetsToTrivisoRecords_EmptyAndNull() {
        List<TrivisoProjetRecord> fromEmpty = TrivisoProjetMapper.mapProjetsToTrivisoRecords(new List<Projet__c>());
        System.assertEquals(0, fromEmpty.size(), 'empty list');
        List<TrivisoProjetRecord> fromNull = TrivisoProjetMapper.mapProjetsToTrivisoRecords(null);
        System.assertEquals(0, fromNull.size(), 'null list');
    }

    @isTest
    static void testMapToExportRecord_AllFields() {
        TrivisoProjetRecord record = new TrivisoProjetRecord();
        record.saisComSalesforceId = 'SFID';
        record.saisComId = 'TRV_ID';
        record.saisComIdentification = 'IDENT';
        record.saisComDescription = 'DESC';
        record.saisComNoCommClient = 'NO_CLIENT';
        record.saisComEtatId = 'ETAT';
        record.saisComGenreProjet = 'GENRE';
        record.saisComFamDesignation = 'FAM';
        record.saisComDateOuvert = '01.01.2024 00:00:00';
        record.saisComDateModif = '02.01.2024 00:00:00';
        record.saisComAdrFactId = 'FACT';
        record.saisComAdrLivrId = 'LIVR';
        record.saisComAdrMoId = 'MO';
        record.saisComAdrArchId = 'ARCH';
        record.saisComAdrRespId = 'RESP';
        record.saisComAdrMandId = 'MAND';
        record.saisComAdrRespProjId = 'RESP_PROJ';
        record.saisComAdrFactContactId = 'CONT_FACT';
        record.saisComAdrFactContactSalesforceId = 'SFID_CONT_FACT';
        record.saisComAdrLivrContactId = 'CONT_LIVR';
        record.saisComAdrLivrContactSalesforceId = 'SFID_CONT_LIVR';
        record.saisComAdrMoContactId = 'CONT_MO';
        record.saisComAdrMoContactSalesforceId = 'SFID_CONT_MO';
        record.saisComAdrArchContactId = 'CONT_ARCH';
        record.saisComAdrArchContactSalesforceId = 'SFID_CONT_ARCH';
        record.saisComSomPrixRevientSansProvision = '1';
        record.saisComSomPrixRevient = '2';
        record.saisComSomOffert = '3';
        record.saisComSomConfirme = '4';
        record.saisComSomCorrectionConfirme = '5';
        record.saisComSomFacture = '6';
        record.saisComSomPaye = '7';
        record.saisComSomDac = '8';
        record.saisComSomPotentielFacturation = '9';
        record.saisComSomAvanceClient = '10';
        record.saisComSomSoldeAPayeCHF = '11';
        Test.startTest();
        Map<String, String> exportRecord = TrivisoProjetMapper.mapToExportRecord(record);
        Test.stopTest();
        System.assertEquals('SFID', exportRecord.get('SAIS_COM_Salesforce_Id'));
        System.assertEquals('TRV_ID', exportRecord.get('SAIS_COM_ID'));
        System.assertEquals('IDENT', exportRecord.get('SAIS_COM_Identification'));
        System.assertEquals('DESC', exportRecord.get('SAIS_COM_Description'));
        System.assertEquals('NO_CLIENT', exportRecord.get('SAIS_COM_No_Comm_client'));
        System.assertEquals('ETAT', exportRecord.get('SAIS_COM_Etat_ID'));
        System.assertEquals('GENRE', exportRecord.get('SAIS_COM_Genre_projet'));
        System.assertEquals('FAM', exportRecord.get('SAIS_COM_Fam_Désignation'));
        System.assertEquals('01.01.2024 00:00:00', exportRecord.get('SAIS_COM_Date_ouvert'));
        System.assertEquals('02.01.2024 00:00:00', exportRecord.get('SAIS_COM_Date_Modif'));
        System.assertEquals('FACT', exportRecord.get('SAIS_COM_ADR_FACT_ID'));
        System.assertEquals('LIVR', exportRecord.get('SAIS_COM_ADR_LIVR_ID'));
        System.assertEquals('MO', exportRecord.get('SAIS_COM_ADR_MO_ID'));
        System.assertEquals('ARCH', exportRecord.get('SAIS_COM_ADR_ARCH_ID'));
        System.assertEquals('RESP', exportRecord.get('SAIS_COM_ADR_RESP_ID'));
        System.assertEquals('MAND', exportRecord.get('SAIS_COM_ADR_MAND_ID'));
        System.assertEquals('RESP_PROJ', exportRecord.get('SAIS_COM_ADR_RESP_PROJ_ID'));
        System.assertEquals('CONT_FACT', exportRecord.get('SAIS_COM_ADR_FACT_CONTACT_ID'));
        // mapToExportRecord n'exporte pas de clé "..._CONTACT_Salesforce_ID" (non présente dans le mapping XML)
        System.assertEquals('CONT_LIVR', exportRecord.get('SAIS_COM_ADR_LIVR_CONTACT_ID'));
        System.assertEquals('CONT_MO', exportRecord.get('SAIS_COM_ADR_MO_CONTACT_ID'));
        System.assertEquals('CONT_ARCH', exportRecord.get('SAIS_COM_ADR_ARCH_CONTACT_ID'));
        // BUG CONNU (present aussi sur testWider) : TrivisoProjetMapper.mapToExportRecord()
        // n'exporte actuellement aucun des champs montants SAIS_COM_SOM_* vers la map XML,
        // malgre le commentaire de la methode qui les liste. A signaler separement.
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Prix_revient_sans_provision'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Prix_revient'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Offert'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Confirmé'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Correction_Confirmé'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Facturé'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Payé'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_DAC'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_potentiel_facturation'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_avance_client'));
        System.assertEquals(null, exportRecord.get('SAIS_COM_SOM_Solde_a_paye_CHF'));
    }
}