test/force-app/main/default/objects/Account/fields/Compte_Facturation__c.field-meta.xml
<CustomField>
    <fullName>Compte_Facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Account/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <label>Identification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/Projet__c.object-meta.xml
<CustomObject>
    <label>Projet</label>
    <nameField>
        <label>Nom projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Projet__c/fields/A_facturer__c.field-meta.xml
<CustomField>
    <fullName>A_facturer__c</fullName>
    <label>A facturer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Adresse_de_Livraison_2__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_Livraison_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact de livraison</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Adresse de Livraison 2)</relationshipLabel>
    <relationshipName>Projets1</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Adresse_de_Livraison__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_Livraison__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse de Livraison</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Adresse de Livraison)</relationshipLabel>
    <relationshipName>Projets5</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Architecte__c.field-meta.xml
<CustomField>
    <fullName>Architecte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Architecte /EG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Architecte)</relationshipLabel>
    <relationshipName>Projets2</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Architecte_EG_Contact__c.field-meta.xml
<CustomField>
    <fullName>Architecte_EG_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact (Architecte/EG)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Architecte / EG - Contact)</relationshipLabel>
    <relationshipName>Projets9</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Avance_client__c.field-meta.xml
<CustomField>
    <fullName>Avance_client__c</fullName>
    <label>Avance client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Calculation_net_avec_provision__c.field-meta.xml
<CustomField>
    <fullName>Calculation_net_avec_provision__c</fullName>
    <label>Calculation PR (avec provisions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Calculation_net_sans_provision__c.field-meta.xml
<CustomField>
    <fullName>Calculation_net_sans_provision__c</fullName>
    <label>Calculation PR (sans provisions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Compte_Facturation__c.field-meta.xml
<CustomField>
    <fullName>Compte_Facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Compte Facturation)</relationshipLabel>
    <relationshipName>Projets3</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Confirme__c.field-meta.xml
<CustomField>
    <fullName>Confirme__c</fullName>
    <label>Confirmé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Correction_confirm__c.field-meta.xml
<CustomField>
    <fullName>Correction_confirm__c</fullName>
    <label>Correction confirmé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Date_de_fermeture__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fermeture__c</fullName>
    <label>Date d&apos;adjudication</label>
    <type>Date</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Etape__c.field-meta.xml
<CustomField>
    <fullName>Etape__c</fullName>
    <label>Étape</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunité</fullName>
                <default>true</default>
                <label>Opportunité</label>
            </value>
            <value>
                <fullName>Attribution</fullName>
            </value>
            <value>
                <fullName>Ouvert</fullName>
            </value>
            <value>
                <fullName>Ouvert (Offre envoyée)</fullName>
                <label>Offre envoyée</label>
            </value>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Confirmé</fullName>
            </value>
            <value>
                <fullName>Exécuté</fullName>
            </value>
            <value>
                <fullName>Facturé</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Pas exécuté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Facturation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facturation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact facturation</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Autre contact)</relationshipLabel>
    <relationshipName>Projets3</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <label>Facturé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Famille_commerciale__c.field-meta.xml
<CustomField>
    <fullName>Famille_commerciale__c</fullName>
    <label>Famille commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Secteur_d_activite__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>fc.00.54 Boutique</fullName>
                <label>Boutique</label>
            </value>
            <value>
                <fullName>fc.00.55 Corner</fullName>
                <label>Corner</label>
            </value>
            <value>
                <fullName>fc.00.56 Shop in shop</fullName>
                <label>Shop-in-shop</label>
            </value>
            <value>
                <fullName>fc.00.57 Pop-up</fullName>
                <label>Pop-up</label>
            </value>
            <value>
                <fullName>fc.00.58 Mobilier de série</fullName>
                <label>Mobilier de série</label>
            </value>
            <value>
                <fullName>fc.00.59 Stands d&apos;exposition</fullName>
                <label>Stand d’exposition</label>
            </value>
            <value>
                <fullName>fc.01.04 Hôtellerie</fullName>
                <label>Hôtellerie</label>
            </value>
            <value>
                <fullName>fc.01.06 Santé</fullName>
                <label>Santé</label>
            </value>
            <value>
                <fullName>fc.01.07 Musées</fullName>
                <label>Musées</label>
            </value>
            <value>
                <fullName>fc.01.08 Commercial</fullName>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>fc.01.09 Immeuble</fullName>
                <label>Immeuble</label>
            </value>
            <value>
                <fullName>fc.01.10 Privé</fullName>
                <label>Privé</label>
            </value>
            <value>
                <fullName>fc.01.14 Administratif</fullName>
                <label>Administratif</label>
            </value>
            <value>
                <fullName>fc.01.16 Scolaire</fullName>
                <label>Scolaire</label>
            </value>
            <value>
                <fullName>fc.01.17 Airkel</fullName>
                <label>Airkel</label>
            </value>
            <value>
                <fullName>fc.01.18 Écrin/PLV</fullName>
                <label>Écrin/PLV</label>
            </value>
            <value>
                <fullName>fc.00.57, Pop-up</fullName>
            </value>
            <value>
                <fullName>Interco</fullName>
            </value>
            <value>
                <fullName>Travaux internes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Genre_Projet_SF__c.field-meta.xml
<CustomField>
    <fullName>Genre_Projet_SF__c</fullName>
    <label>Typologie projet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Projet classique</fullName>
            </value>
            <value>
                <fullName>Projet multiple</fullName>
            </value>
            <value>
                <fullName>Projet PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Maitre_d_ouvrage__c.field-meta.xml
<CustomField>
    <fullName>Maitre_d_ouvrage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client/MO</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projets (Maitre d’ouvrage)</relationshipLabel>
    <relationshipName>Projets1</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Maitre_d_ouvrage_Contact__c.field-meta.xml
<CustomField>
    <fullName>Maitre_d_ouvrage_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact (Client/MO)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Maitre d’ouvrage - Contact)</relationshipLabel>
    <relationshipName>Projets8</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Mandant__c.field-meta.xml
<CustomField>
    <fullName>Mandant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mandant</label>
    <referenceTo>Soci_t_du_groupe__c</referenceTo>
    <relationshipLabel>Projets</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant estimatif</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Numero_projet__c.field-meta.xml
<CustomField>
    <fullName>Numero_projet__c</fullName>
    <label>Numéro projet</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Offert__c.field-meta.xml
<CustomField>
    <fullName>Offert__c</fullName>
    <label>Offert</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Paiement_client_recevoir__c.field-meta.xml
<CustomField>
    <fullName>Paiement_client_recevoir__c</fullName>
    <label>À recevoir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Paye__c.field-meta.xml
<CustomField>
    <fullName>Paye__c</fullName>
    <label>Payé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Reference_client__c.field-meta.xml
<CustomField>
    <fullName>Reference_client__c</fullName>
    <label>Référence client</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Projet__c/fields/Responsable_commercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable commercial</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets (Responsable commercial)</relationshipLabel>
    <relationshipName>ProjetsTiDy</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Responsable_Projet_Contact__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Projet_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sous-traitant 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projets</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/SAIS_com_ID__c.field-meta.xml
<CustomField>
    <fullName>SAIS_com_ID__c</fullName>
    <label>SAIS _com ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

test/force-app/main/default/objects/Projet__c/fields/Type_projet__c.field-meta.xml
<CustomField>
    <fullName>Type_projet__c</fullName>
    <label>Genre projet</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Soci_t_du_groupe__c/Soci_t_du_groupe__c.object-meta.xml
<CustomObject>
    <label>Société du groupe</label>
    <nameField>
        <label>Nom de Société du groupe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sociétés du groupe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Soci_t_du_groupe__c/fields/IdentifiantSoci_t_grpupe__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantSoci_t_grpupe__c</fullName>
    <label>IdentifiantSociétégrpupe</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

test/force-app/main/default/classes/TrivisoProjetMapper.cls
public class TrivisoProjetMapper {

    public static List<TrivisoProjetRecord> mapProjetsToTrivisoRecords(List<Projet__c> projets) {
        List<TrivisoProjetRecord> trivisoRecords = new List<TrivisoProjetRecord>();
        
        if (projets == null || projets.isEmpty()) {
            System.debug('TRIVISO_LOG: No projets to map');
            return trivisoRecords;
        }
        
        System.debug('TRIVISO_LOG: Mapping ' + projets.size() + ' Projet__c to TrivisoProjetRecord for export');
        
        for (Projet__c projet : projets) {
            TrivisoProjetRecord record = mapFromProjet(projet);
            trivisoRecords.add(record);
        }
        
        System.debug('TRIVISO_LOG: Mapped ' + trivisoRecords.size() + ' Projet__c to TrivisoProjetRecord');
        
        return trivisoRecords;
    }
    
    public static TrivisoProjetRecord mapFromProjet(Projet__c projet) {
        TrivisoProjetRecord record = new TrivisoProjetRecord();
        
        // SAIS_COM_Salesforce_Id - ID Salesforce du projet
        record.saisComSalesforceId = projet.Id != null ? String.valueOf(projet.Id) : '';
        
        record.saisComId = projet.SAIS_com_ID__c != null ? projet.SAIS_com_ID__c : '';
        
        // SAIS_COM_Identification - Numéro du projet (Numero_projet__c ou Name)
        record.saisComIdentification = projet.Numero_projet__c != null ? projet.Numero_projet__c : '';
        
        // SAIS_COM_Description - Nom/Description du projet (Name)
        record.saisComDescription = projet.Name != null ? projet.Name : '';
        
        // SAIS_COM_No_Comm_client - Référence client
        record.saisComNoCommClient = projet.Reference_client__c != null ? projet.Reference_client__c : '';
        
        // SAIS_COM_Etat_ID - ID de l'étape du projet (Etape__c)
        record.saisComEtatId = projet.Etape__c != null ? String.valueOf(projet.Etape__c) : '';
        
        // SAIS_COM_Genre_projet - Genre du projet (Type_projet__c)
        record.saisComGenreProjet = projet.Type_projet__c != null ? projet.Type_projet__c : '';
        
        // SAIS_COM_Fam_Désignation - Famille commerciale
        record.saisComFamDesignation = projet.Famille_commerciale__c != null ? projet.Famille_commerciale__c : '';
        
        // SAIS_COM_Date_ouvert - Date d'ouverture (Date_de_fermeture__c)
        if (projet.Date_de_fermeture__c != null) {
            record.saisComDateOuvert = formatDateForXml(projet.Date_de_fermeture__c);
        } else {
            record.saisComDateOuvert = '';
        }
        
        // SAIS_COM_Date_Modif - Date de dernière modification
        if (projet.LastModifiedDate != null) {
            record.saisComDateModif = formatDateForXml(projet.LastModifiedDate.date());
        } else {
            record.saisComDateModif = '';
        }
        
        // SAIS_COM_ADR_FACT_ID - ID Triviso du nom du compte (via relation Account)
        record.saisComAdrFactId = (projet.Compte_Facturation__r != null && projet.Compte_Facturation__r.Identification__c != null) ? projet.Compte_Facturation__r.Identification__c : '';
        record.saisComAdrFactSalesforceId = projet.Compte_Facturation__c != null ? String.valueOf(projet.Compte_Facturation__c) : '';

        // SAIS_COM_ADR_LIVR_ID - ID Triviso de l'adresse de livraison (via relation)
        record.saisComAdrLivrId = (projet.Adresse_de_Livraison__r != null && projet.Adresse_de_Livraison__r.Identification__c != null) ? projet.Adresse_de_Livraison__r.Identification__c : '';
        record.saisComAdrLivrSalesforceId = projet.Adresse_de_Livraison__c != null ? String.valueOf(projet.Adresse_de_Livraison__c) : '';

        // SAIS_COM_ADR_MO_ID - ID Triviso du maître d'ouvrage (via relation)
        record.saisComAdrMoId = (projet.Maitre_d_ouvrage__r != null && projet.Maitre_d_ouvrage__r.Identification__c != null) ? projet.Maitre_d_ouvrage__r.Identification__c : '';
        record.saisComAdrMoSalesforceId = projet.Maitre_d_ouvrage__c != null ? String.valueOf(projet.Maitre_d_ouvrage__c) : '';

        // SAIS_COM_ADR_ARCH_ID - ID Triviso de l'architecte (via relation Account)
        record.saisComAdrArchId = (projet.Architecte__r != null && projet.Architecte__r.Identification__c != null) ? projet.Architecte__r.Identification__c : '';
        record.saisComAdrArchSalesforceId = projet.Architecte__c != null ? String.valueOf(projet.Architecte__c) : '';

        // SAIS_COM_ADR_RESP_ID - ID Triviso du responsable commercial (via relation)
        record.saisComAdrRespId = (projet.Responsable_commercial__r != null && projet.Responsable_commercial__r.Identification__c != null) ? projet.Responsable_commercial__r.Identification__c : '';
        record.saisComAdrRespSalesforceId = projet.Responsable_commercial__c != null ? String.valueOf(projet.Responsable_commercial__c) : '';

        // SAIS_COM_ADR_MAND_ID - ID Triviso du mandant (via relation Mandant__c)
        record.saisComAdrMandId = (projet.Mandant__r != null && projet.Mandant__r.IdentifiantSoci_t_grpupe__c != null) ? projet.Mandant__r.IdentifiantSoci_t_grpupe__c : '';
        record.saisComAdrMandSalesforceId = projet.Mandant__c != null ? String.valueOf(projet.Mandant__c) : '';

        // SAIS_COM_ADR_RESP_PROJ_ID - ID Triviso du chef de projet (via relation Contact)
        record.saisComAdrRespProjId = (projet.Responsable_Projet_Contact__r != null && projet.Responsable_Projet_Contact__r.Identification__c != null) ? projet.Responsable_Projet_Contact__r.Identification__c : '';
        record.saisComAdrRespProjSalesforceId = projet.Responsable_Projet_Contact__c != null ? String.valueOf(projet.Responsable_Projet_Contact__c) : '';

        // SAIS_COM_ADR_FACT_CONTACT_ID - ID Triviso du contact facturation
        record.saisComAdrFactContactId = (projet.Facturation_Contact__r != null && projet.Facturation_Contact__r.Identification__c != null) ? projet.Facturation_Contact__r.Identification__c : '';

        // SAIS_COM_ADR_LIVR_CONTACT_ID - ID Triviso du contact adresse de livraison
        record.saisComAdrLivrContactId = (projet.Adresse_de_Livraison_2__r != null && projet.Adresse_de_Livraison_2__r.Identification__c != null) ? projet.Adresse_de_Livraison_2__r.Identification__c : '';

        // SAIS_COM_ADR_MO_CONTACT_ID - ID Triviso du contact maître d'ouvrage
        record.saisComAdrMoContactId = (projet.Maitre_d_ouvrage_Contact__r != null && projet.Maitre_d_ouvrage_Contact__r.Identification__c != null) ? projet.Maitre_d_ouvrage_Contact__r.Identification__c : '';

        // SAIS_COM_ADR_ARCH_CONTACT_ID - ID Triviso du contact architecte
        record.saisComAdrArchContactId = (projet.Architecte_EG_Contact__r != null && projet.Architecte_EG_Contact__r.Identification__c != null) ? projet.Architecte_EG_Contact__r.Identification__c : '';

        record.genreProjetSf = projet.Genre_Projet_SF__c != null ? projet.Genre_Projet_SF__c : '';

        // Montants - Mapping depuis les champs Decimal de Projet__c
        record.saisComSomPrixRevientSansProvision = formatDecimalForXml(projet.Calculation_net_sans_provision__c);
        record.saisComSomPrixRevient = formatDecimalForXml(projet.Calculation_net_avec_provision__c);
        record.saisComSomOffert = formatDecimalForXml(projet.Offert__c);
        record.saisComSomConfirme = formatDecimalForXml(projet.Confirme__c);
        record.saisComSomCorrectionConfirme = formatDecimalForXml(projet.Correction_confirm__c);
        record.saisComSomFacture = formatDecimalForXml(projet.Facture__c);
        record.saisComSomPaye = formatDecimalForXml(projet.Paye__c);
        record.saisComSomDac = formatDecimalForXml(projet.Montant__c);
        record.saisComSomPotentielFacturation = formatDecimalForXml(projet.A_facturer__c);
        record.saisComSomAvanceClient = formatDecimalForXml(projet.Avance_client__c);
        record.saisComSomSoldeAPayeCHF = formatDecimalForXml(projet.Paiement_client_recevoir__c);
        
        return record;
    }
    
    /**
     * Convertit un TrivisoProjetRecord en Map pour l'export XML
     * 
     * IMPORTANT: L'ordre des champs doit correspondre exactement à field_names dans projet_import_module.py:
     * 1. SAIS_COM_Salesforce_Id
     * 2. SAIS_COM_ID
     * 3. SAIS_COM_Identification
     * 4. SAIS_COM_Description
     * 5. SAIS_COM_No_Comm_client
     * 6. SAIS_COM_Etat_ID
     * 7. SAIS_COM_Genre_projet
     * 8. SAIS_COM_Fam_Désignation
     * 9. SAIS_COM_Date_ouvert
     * 10. SAIS_COM_Date_Modif
     * 11. SAIS_COM_ADR_FACT_ID
     * 12. SAIS_COM_ADR_LIVR_ID
     * 13. SAIS_COM_ADR_MO_ID
     * 14. SAIS_COM_ADR_ARCH_ID
     * 15. SAIS_COM_ADR_RESP_ID
     * 16. SAIS_COM_ADR_MAND_ID
     * 17. SAIS_COM_ADR_RESP_PROJ_ID
     * 18. SAIS_COM_SOM_Prix_revient_sans_provision
     * 19. SAIS_COM_SOM_Prix_revient
     * 20. SAIS_COM_SOM_Offert
     * 21. SAIS_COM_SOM_Confirmé
     * 22. SAIS_COM_SOM_Correction_Confirmé
     * 23. SAIS_COM_SOM_Facturé
     * 24. SAIS_COM_SOM_Payé
     * 25. SAIS_COM_SOM_DAC
     * 26. SAIS_COM_SOM_potentiel_facturation
     * 27. SAIS_COM_SOM_avance_client
     * 28. SAIS_COM_SOM_Solde_a_paye_CHF
     * 
     * Note: L'ordre dans la Map n'a pas d'importance car le script Python utilise field_names pour définir l'ordre dans le XML
     */
    public static Map<String, String> mapToExportRecord(TrivisoProjetRecord record) {
        Map<String, String> exportRecord = new Map<String, String>();
        
        // Ordre correspondant à field_names dans projet_import_module.py
        exportRecord.put('SAIS_COM_Salesforce_Id', record.saisComSalesforceId != null ? record.saisComSalesforceId : '');
        exportRecord.put('SAIS_COM_ID', record.saisComId != null ? record.saisComId : '');
        exportRecord.put('SAIS_COM_Identification', record.saisComIdentification != null ? record.saisComIdentification : '');
        exportRecord.put('SAIS_COM_Description', record.saisComDescription != null ? record.saisComDescription : '');
        exportRecord.put('SAIS_COM_No_Comm_client', record.saisComNoCommClient != null ? record.saisComNoCommClient : '');
        exportRecord.put('SAIS_COM_Etat_ID', record.saisComEtatId != null ? record.saisComEtatId : '');
        exportRecord.put('SAIS_COM_Genre_projet', record.saisComGenreProjet != null ? record.saisComGenreProjet : '');
        exportRecord.put('SAIS_COM_Fam_Désignation', record.saisComFamDesignation != null ? record.saisComFamDesignation : '');
        exportRecord.put('SAIS_COM_Date_ouvert', record.saisComDateOuvert != null ? record.saisComDateOuvert : '');
        exportRecord.put('SAIS_COM_Date_Modif', record.saisComDateModif != null ? record.saisComDateModif : '');
        exportRecord.put('SAIS_COM_ADR_FACT_ID', record.saisComAdrFactId != null ? record.saisComAdrFactId : '');
        exportRecord.put('SAIS_COM_ADR_FACT_Salesforce_ID', record.saisComAdrFactSalesforceId != null ? record.saisComAdrFactSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_LIVR_ID', record.saisComAdrLivrId != null ? record.saisComAdrLivrId : '');
        exportRecord.put('SAIS_COM_ADR_LIVR_Salesforce_ID', record.saisComAdrLivrSalesforceId != null ? record.saisComAdrLivrSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_MO_ID', record.saisComAdrMoId != null ? record.saisComAdrMoId : '');
        exportRecord.put('SAIS_COM_ADR_MO_Salesforce_ID', record.saisComAdrMoSalesforceId != null ? record.saisComAdrMoSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_ARCH_ID', record.saisComAdrArchId != null ? record.saisComAdrArchId : '');
        exportRecord.put('SAIS_COM_ADR_ARCH_Salesforce_ID', record.saisComAdrArchSalesforceId != null ? record.saisComAdrArchSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_RESP_ID', record.saisComAdrRespId != null ? record.saisComAdrRespId : '');
        exportRecord.put('SAIS_COM_ADR_RESP_Salesforce_ID', record.saisComAdrRespSalesforceId != null ? record.saisComAdrRespSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_MAND_ID', record.saisComAdrMandId != null ? record.saisComAdrMandId : '');
        exportRecord.put('SAIS_COM_ADR_MAND_Salesforce_ID', record.saisComAdrMandSalesforceId != null ? record.saisComAdrMandSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_RESP_PROJ_ID', record.saisComAdrRespProjId != null ? record.saisComAdrRespProjId : '');
        exportRecord.put('SAIS_COM_ADR_RESP_PROJ_Salesforce_ID', record.saisComAdrRespProjSalesforceId != null ? record.saisComAdrRespProjSalesforceId : '');
        exportRecord.put('SAIS_COM_ADR_FACT_CONTACT_ID', record.saisComAdrFactContactId != null ? record.saisComAdrFactContactId : '');
        exportRecord.put('SAIS_COM_ADR_LIVR_CONTACT_ID', record.saisComAdrLivrContactId != null ? record.saisComAdrLivrContactId : '');
        exportRecord.put('SAIS_COM_ADR_MO_CONTACT_ID', record.saisComAdrMoContactId != null ? record.saisComAdrMoContactId : '');
        exportRecord.put('SAIS_COM_ADR_ARCH_CONTACT_ID', record.saisComAdrArchContactId != null ? record.saisComAdrArchContactId : '');
        exportRecord.put('GENRE_PROJET_SF', record.genreProjetSf != null ? record.genreProjetSf : '');

        return exportRecord;
    }
    
    private static String formatDateForXml(Date dateValue) {
        if (dateValue == null) {
            return '';
        }
        // Format: DD.MM.YYYY HH:MM:SS (on met 00:00:00 pour l'heure car Date n'a pas d'heure)
        Integer dayInt = dateValue.day();
        Integer monthInt = dateValue.month();
        Integer yearInt = dateValue.year();
        String day = dayInt < 10 ? '0' + String.valueOf(dayInt) : String.valueOf(dayInt);
        String month = monthInt < 10 ? '0' + String.valueOf(monthInt) : String.valueOf(monthInt);
        String year = String.valueOf(yearInt);
        return day + '.' + month + '.' + year + ' 00:00:00';
    }
    
    private static String formatDecimalForXml(Decimal decimalValue) {
        if (decimalValue == null) {
            return '';
        }
        return String.valueOf(decimalValue);
    }
}