prod/force-app/main/default/objects/Simap_Cantons__c/Simap_Cantons__c.object-meta.xml
<CustomObject>
    <label>Simap Canton</label>
    <nameField>
        <label>Simap Cantons Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Cantons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/force-app/main/default/objects/Simap_Cantons__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <label>Abbreviation</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

test/force-app/main/default/objects/Simap_Code_CFC_BKP__c/Simap_Code_CFC_BKP__c.object-meta.xml
<CustomObject>
    <label>Simap Code CFC-BKP</label>
    <nameField>
        <label>Simap Code CFC-BKP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Codes CFC-BKP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/force-app/main/default/objects/Simap_Code_CFC_BKP__c/fields/Code_CFC_BKP__c.field-meta.xml
<CustomField>
    <fullName>Code_CFC_BKP__c</fullName>
    <label>Code CFC-BKP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Simap_Code_CPV__c/Simap_Code_CPV__c.object-meta.xml
<CustomObject>
    <label>Simap Code CPV</label>
    <nameField>
        <label>Simap Code CPV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Codes CPV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/force-app/main/default/objects/Simap_Code_CPV__c/fields/Code_CPV__c.field-meta.xml
<CustomField>
    <fullName>Code_CPV__c</fullName>
    <label>Code CPV</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Simap_Type_de_Contrat__c/Simap_Type_de_Contrat__c.object-meta.xml
<CustomObject>
    <label>Simap Type de Contrat</label>
    <nameField>
        <label>Simap Type de Contrat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Types de Contrat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/force-app/main/default/objects/Simap_Type_de_Contrat__c/fields/inclus_dans_API_SIMAP__c.field-meta.xml
<CustomField>
    <fullName>inclus_dans_API_SIMAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>inclus dans API SIMAP</label>
    <type>Checkbox</type>
</CustomField>

prod/force-app/main/default/objects/Simap_Type_de_Contrat__c/fields/Nom_API_param__c.field-meta.xml
<CustomField>
    <fullName>Nom_API_param__c</fullName>
    <label>Nom API param</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/objects/Simap_Type_de_Publication__c/Simap_Type_de_Publication__c.object-meta.xml
<CustomObject>
    <label>Simap Type de Publication</label>
    <nameField>
        <label>Type de Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Types de publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/force-app/main/default/objects/Simap_Type_de_Publication__c/fields/simap_value__c.field-meta.xml
<CustomField>
    <fullName>simap_value__c</fullName>
    <label>simap value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

prod/force-app/main/default/classes/SimapUtils.cls
public class SimapUtils {

    public class SimapUtilsException extends Exception {}

    public static final Integer CUSTOM_FIELD_MAX_LENGTH = 225;
    public static final String ADDRESS_SEPARATOR = ', ';
    public static final Map<String, String> COUNTRY_LABELS = new Map<String, String> {
        'CH' => 'Suisse'
    };

    public static List<SObject> getSelectedCantonalEntities() {
        return [
            SELECT 
                Id,
                Name,
                simap_id__c,
                Abbreviation__c,
                inclus_dans_API_SIMAP__c
            FROM
                Simap_Cantons__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<SObject> getSelectedProjectSubTypes() {
        return [
            SELECT
                Id,
                Name,
                Nom_API_param__c,
                inclus_dans_API_SIMAP__c
            FROM
                Simap_Type_de_Contrat__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<Simap_Code_CPV__c> getSelectedSimapCodesCPV() {
        return [
            SELECT
                Id,
                Name,
                Code_CPV__c,
                inclus_dans_API_SIMAP__c
            FROM
                Simap_Code_CPV__c
            WHERE
                inclus_dans_API_SIMAP__c = true
        ];
    }

    public static Simap_Code_CFC_BKP__c getDefaultCodeCfcBkp() {
        List<Simap_Code_CFC_BKP__c> codeCfcBkps = [
            SELECT
                Id,
                Code_CFC_BKP__c,
                inclus_dans_API_SIMAP__c
            FROM
                Simap_Code_CFC_BKP__c
            ];
        
        if (codeCfcBkps.isEmpty()) {
            throw new SimapUtilsException('No code CFC / BKP found. at least one record should be present');
        }

        if (codeCfcBkps.size() > 1) {
            throw new SimapUtilsException('Multiple code CFC / BKP found. only one record should be present');
        }

        return codeCfcBkps[0];
    }

    public static List<Simap_Type_de_Publication__c> getDefaultTypeDePublication() {
        return [
            SELECT
                Id,
                Name,
                inclus_dans_API_SIMAP__c,
                simap_value__c
            FROM
                Simap_Type_de_Publication__c
            WHERE
                inclus_dans_API_SIMAP__c = true
        ];
    }

    public static String checkAndTrimLength(String fieldValue) {
        if (fieldValue == null) {
            return null;
        }
        fieldValue = fieldValue.trim();
        return fieldValue.length() > CUSTOM_FIELD_MAX_LENGTH ? fieldValue.substring(0, CUSTOM_FIELD_MAX_LENGTH) : fieldValue;
    }

    public static String getValidField(SimapHeadersService.SimapSwissLangSet fieldMap) {
        if (fieldMap == null) {
            return '';
        }
        if (fieldMap.fr != null && fieldMap.fr != '') {
            return fieldMap.fr;
        } else if (fieldMap.de != null && fieldMap.de != '') {
            return fieldMap.de;
        } else if (fieldMap.it != null && fieldMap.it != '') {
            return fieldMap.it;
        } else if (fieldMap.en != null && fieldMap.en != '') {
            return fieldMap.en;
        } else {
            return null;
        }
    }

    public static String addressConverter(SimapPublicationDetailService.SimapAdress addr) {
        if (
            addr?.city == null ||
            addr?.postalCode == null ||
            addr?.street == null
        ) {
            return null;
        }
        String parsedAddress = '';

        String parsedStreet = getValidField(addr.street);
        String parsedCity = getValidField(addr.city);

        List<String> addressParts = new List<String> {
            parsedStreet,
            parsedCity,
            addr.cantonId,
            addr.countryId,
            addr.postalCode
        };

        for(String addressPart : addressParts) {
            if(!String.isBlank(addressPart) && addressPart != null) {
                parsedAddress += addressPart + ADDRESS_SEPARATOR;
            }
        }

        parsedAddress = parsedAddress.removeEnd(ADDRESS_SEPARATOR);
        return parsedAddress;
    }

    // the order address of the search payload has no street, so it is formatted
    // as 'postalCode city, cantonId, country' instead of going through addressConverter
    public static String orderAddressConverter(SimapHeadersService.SimapOrderAddress addr) {
        if (addr == null) {
            return null;
        }

        String locality = '';
        for (String localityPart : new List<String> { addr.postalCode, getValidField(addr.city) }) {
            if (!String.isBlank(localityPart)) {
                locality += localityPart + ' ';
            }
        }
        locality = locality.trim();

        String country = COUNTRY_LABELS.containsKey(addr.countryId)
            ? COUNTRY_LABELS.get(addr.countryId)
            : addr.countryId;

        String parsedAddress = '';
        for (String addressPart : new List<String> { locality, addr.cantonId, country }) {
            if (!String.isBlank(addressPart)) {
                parsedAddress += addressPart + ADDRESS_SEPARATOR;
            }
        }

        return checkAndTrimLength(parsedAddress.removeEnd(ADDRESS_SEPARATOR));
    }

    public static String getValidPublicationTitle(SimapHeadersService.PublicationDeserializer publication) {
        return checkAndTrimLength(getValidField(publication.title));
    }

    public static String getValidPublicationProcOfficeName(SimapHeadersService.PublicationDeserializer publication) {
        return checkAndTrimLength(getValidField(publication.procOfficeName));
    }

    public static String getValidCantonValue(SimapPublicationDetailService.ProjectInfo projectInfo) {
        if (projectInfo.procOfficeAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.procOfficeAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }
        if (projectInfo.procurementRecipientAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.procurementRecipientAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }
        if (projectInfo.offerAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.offerAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }

        return null;
    }

    public static String getCantonNameByAbbreviation(String cantonId) {
        List<SObject> simapCantonalEntities = SimapUtils.getSelectedCantonalEntities();
        for (SObject entity : simapCantonalEntities) {
            if ((String) entity.get('Abbreviation__c') == cantonId) {
                return (String) entity.get('Name');
            }
        }
        return null;
    }

}