prod/force-app/main/default/objects/Account/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <label>Identification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

test/force-app/main/default/objects/Account/fields/Triviso_status__c.field-meta.xml
<CustomField>
    <fullName>Triviso_status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triviso Status</label>
    <type>Checkbox</type>
</CustomField>

test/force-app/main/default/classes/UpdateAccountTrivisoBatch.cls
public class UpdateAccountTrivisoBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id FROM Account WHERE Identification__c != null'
        );
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
        for (Account acc : scope) {
            acc.Triviso_status__c = true;
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch UpdateAccountTrivisoBatch terminé');
    }
}